# Generated by Django 2.2.4 on 2021-05-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='released_date',
            field=models.DateTimeField(),
        ),
    ]
