# Generated by Django 2.2.4 on 2021-05-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0002_auto_20210525_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='released_date',
            field=models.CharField(max_length=255),
        ),
    ]
