# Generated by Django 2.2.4 on 2021-05-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_app', '0003_auto_20210525_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
    ]
